- name: Install kubectl 
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl"
    dest: "{{ kubectl_dest }}/kubectl"
    mode: '0777'