Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "ServiceDiscovery"
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.network "forwarded_port", guest: 9000, host: 9000 # Portainer

  # Provisioning with ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yaml"
  end

   config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
   end

end
