version: "3.8"
services:
  nginx:
    build: './nginx'
    ports:
    - "8000:80"
    volumes: 
      - logs_v:/var/log/nginx/

  filebeat:
    build: './filebeat'
    ports:
      - 5044:5044
    expose: 
      - 5044
    volumes:
      - type: volume 
        source: logs_v 
        target: /var/log/nginx
        read_only: true
    networks:
      - elastic

  logstash:
    build: './logstash'
    hostname: logstash
    networks:
      - elastic

  es01:
      build: './elasticsearch'
      container_name: es01
      hostname: elasticsearch
      environment:
        - node.name=es01
        - cluster.name=es-docker-cluster
        - discovery.seed_hosts=es02,es03
        - cluster.initial_master_nodes=es01,es02,es03
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - data01:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
      networks:
        - elastic

  es02:
    build: './elasticsearch'
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9201:9201
    networks:
      - elastic

  es03:
    build: './elasticsearch'
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    ports:
      - 9202:9202
    networks:
      - elastic

  kib01:
    build: './kibana'
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic


    
    
    
networks:
  elastic:
    driver: bridge


  
volumes:
  logs_v:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local